site_name: Voidc Pages
site_url: https://voidc-lab.github.io/pages

theme:
  name: material
  palette:
    primary: white
  features:
    - navigation.tabs

markdown_extensions:
  - pymdownx.tilde
  - pymdownx.emoji

nav:
  - Home: index.md
  - Getting started:
    - Installation: getting-started.md

